name: 功能请求 / Function request
description: 用于提议新功能或改进 / Used to suggest new features or improvements
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: miaoshu-2
    attributes:
      label: "功能描述 / Feature Description"
      description: "简要描述你希望添加的功能。 / A brief description of the feature you want to add."
      placeholder: "简要描述你希望添加的功能。"
    validations:
      required: true

  - type: input
    id: motivation
    attributes:
      label: "动机 / Motivation"
      description: "为什么需要这个功能？/ Why is this feature needed?"
      placeholder: "描述动机..."
    validations:
      required: true

  - type: input
    id: alternatives
    attributes:
      label: "替代方案 / Alternatives"
      description: "是否有其他方法可以实现类似的功能？/ Are there any alternative ways to achieve similar functionality?"
      placeholder: "描述替代方案..."
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息 / Additional Information"
      description: "其他可能有用的信息。 / Any other information that might be useful."
      placeholder: "输入附加信息..."
    validations:
      required: false
